### ISSUE TITLE
R8 missing in BOM

### ISSUE THREAD

**Issue by bbsan2k** [Chobrenga/N64-SpyDVI#1]
Hi,
Thanks for this great project!
Is it possible, that R8 is missing in the BOM file?

**Comment by Chobrenga** [comment]
That was intentional. It is there so there are pads to add a 22k pull-up if there are issues with the FLASH_CS/BOOT signal. The RP2040 has an internal 60k 20% pull-up on that line.

If you're planning to produce the board as it sits, I must warn you I've been made aware of several design oversights and it may not work at all. I'm fed up with EasyEDA crashing also, and am currently porting the project to Kicad.

**Comment by bbsan2k** [comment]
Thanks for your reply! That’s really good to know - I guess I’ll wait for the new version then😉
I was looking for exactly this kind of board😊
